GIT-49 Implement results component
gitguesser/gitguesser pull request #24
Opened 2023-06-09 10:42 UTC by Virtover

2023-06-09 10:43 UTC, Virtover reviewed
pre-commit.ci autofix

2023-06-11 23:50 UTC, lukaszsmolinski commented on frontend/src/components/Results.js
> +        const response = await fetch(`${BACKEND_URL}/repository/${state.gameId}/`);
The id of the repository, not the game, should be used here.

2023-06-11 23:56 UTC, lukaszsmolinski requested changes

2023-06-11 23:56 UTC, lukaszsmolinski commented on frontend/src/components/Results.js
> +          `${BACKEND_URL}/repository/${state.gameId}/`
I think that the id of the repository, not the game, should be used here.

2023-06-11 23:56 UTC, lukaszsmolinski commented on frontend/src/components/Results.js
Can you also make it possible to go back to the home screen?

2023-06-12 10:32 UTC, lukaszsmolinski approved these changes

2023-06-12 12:52 UTC, kate20031 approved these changes

2023-06-14 12:08 UTC, zemdam approved these changes

2023-06-15 09:44 UTC, merged