Git 48 implement game component
gitguesser/gitguesser pull request #25
Opened 2023-06-10 11:06 UTC by kate20031

2023-06-12 00:22 UTC, lukaszsmolinski commented on frontend/src/components/Game.js
> +            setAnswerSubmitted(true);
I don't think we need the `answerSubmitted` flag. I think that after submitting the answer, the player should be automatically redirected to the results.

2023-06-12 00:22 UTC, lukaszsmolinski commented on frontend/src/components/Game.js
> +        </button>
Can you make this button disabled when the player is already in the root directory?

2023-06-12 00:22 UTC, lukaszsmolinski commented on frontend/src/components/Game.js
> +          onClick={() => handleSubmit(answer)}
Can you make this button disabled when the player hasn't chosen any directory yet?

2023-06-12 00:44 UTC, lukaszsmolinski commented on frontend/src/components/Game.js
> +  const [currentPath, setCurrentPath] = useState("gitguesser");
The path shouldn't begin with `gitguesser` in every repository.

2023-06-13 14:39 UTC, Virtover requested changes
1) Add the name of the file whose location we want to guess
2) Redirect to Results (with sending gameId) when answer is submitted

2023-06-13 18:13 UTC, Virtover requested changes
![image](https://github.com/gitguesser/gitguesser/assets/16001791/c02adc7c-5bb8-4e9b-b362-7845d840449f)
in this case (and others when I click directory without subdirectories), location "/frontend/src/components" is not chosen when I click submit

2023-06-15 09:50 UTC, Virtover requested changes
-> Answer should be full path, but only folder name is send as an answer. This should be changed, otherwise game will not work.

-> Choose button is in the center when there is no back button, and flies to the right when there is back button. I think it would be good to make it staying in one place.

2023-06-17 13:29 UTC, Virtover approved these changes

2023-06-17 18:18 UTC, lukaszsmolinski approved these changes

2023-06-17 19:20 UTC, merged